# Generated by Django 5.0.6 on 2025-08-07 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_store', '0003_alter_cars_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='car_store.size'),
        ),
    ]
